const LEDGER_ENTRY_TYPES = {
   DEBIT: "DEBIT",
   CREDIT: "CREDIT",
}

const LEDGER_BALANCE_TYPES = {
   AVAILABLE: "AVAILABLE",
   PENDING: "PENDING",
   LOCKED: "LOCKED",
}

const LEDGER_OWNER_TYPES = {
   USER: "USER",
   TREASURY: "TREASURY",
   PLATFORM: "PLATFORM",
}

const OPERATIONS = {
   INTERNAL_TRANSFER: "INTERNAL_TRANSFER",

   BANK_DEPOSIT: "BANK_DEPOSIT",
   BANK_WITHDRAWAL: "BANK_WITHDRAWAL",

   CRYPTO_DEPOSIT: "CRYPTO_DEPOSIT",
   CRYPTO_WITHDRAWAL: "CRYPTO_WITHDRAWAL",

   BUY: "BUY",
   SELL: "SELL",

   FEE: "FEE",

   REWARD: "REWARD",

   ADJUSTMENT: "ADJUSTMENT",

   TREASURY_REBALANCE: "TREASURY_REBALANCE",
}

const BANK_PROVIDERS = {
   NOMBA: "NOMBA",
   PAYSTACK: "PAYSTACK",
   MONNIFY: "MONNIFY",
}

const BANK_ACCOUNT_STATUS = {
   PENDING: "PENDING",
   ACTIVE: "ACTIVE",
   INACTIVE: "INACTIVE",
   SUSPENDED: "SUSPENDED",
   CLOSED: "CLOSED",
}

module.exports = {
   BANK_ACCOUNT_STATUS,
   BANK_PROVIDERS,
   OPERATIONS,
   LEDGER_ENTRY_TYPES,
   LEDGER_BALANCE_TYPES,
   LEDGER_OWNER_TYPES,
   USER_STATUS: {
      ACTIVE: "ACTIVE",
      SUSPENDED: "SUSPENDED",
      BLOCKED: "BLOCKED",
      PENDING: "PENDING",
   },

   KYC_STATUS: {
      NOT_STARTED: "NOT_STARTED",
      PENDING: "PENDING",
      VERIFIED: "VERIFIED",
      REJECTED: "REJECTED",
   },

   USER_TIERS: {
      TIER_0: "TIER_0",
      TIER_1: "TIER_1",
      TIER_2: "TIER_2",
      TIER_3: "TIER_3",
   },

   TRANSACTION_STATUS: {
      PENDING: "PENDING",
      PROCESSING: "PROCESSING",
      SUCCESS: "SUCCESS",
      FAILED: "FAILED",
      CANCELLED: "CANCELLED",
   },

   ASSET_TYPES: {
      FIAT: "FIAT",
      CRYPTO: "CRYPTO",
      STABLECOIN: "STABLECOIN",
   },

   CHAIN_CODES: {
      BSC: "BSC",
      ETH: "ETH",
      BASE: "BASE",
      ARBITRUM: "ARBITRUM",
   },
}
